SDC-2866: Error out gracefully if java is not found in _sdc script
Change-Id: I3e248707ef88ad57ecbcf0f6a95aa0789be946c6
Reviewed-on: https://review.streamsets.net/2762
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Bryan Duxbury <bryan@streamsets.com>

diff --git a/dist/src/main/libexec/_sdc b/dist/src/main/libexec/_sdc
--- a/dist/src/main/libexec/_sdc
+++ b/dist/src/main/libexec/_sdc
@@ -131,9 +131,15 @@ fi
 
 if [ -z "$JAVA_HOME" ]
 then
-  JAVA=`which java`
+  JAVA=`which java 2> /dev/null`
 else
   JAVA="$JAVA_HOME/bin/java"
+fi
+
+if [ -z "$JAVA" ]
+then
+  echo "Can't find java, please set JAVA_HOME pointing to your java installation"
+  exit 1
 fi
 
 SDC_POLICY_FILE=""
