SDC-4767: Make a check to see what JDK vendor is being used and die if it's OpenJDK
* Added detection of JDK vendor.
* SDC will die on start unless Oracle JDK is detected.
* User can override this in sdc-env.sh by setting property.
* Tested on both Oracle JDK and OpenJDK (version 8).

Change-Id: Ib89b15399066d42a79600402898494176a2fd148
Reviewed-on: https://review.streamsets.net/8269
Reviewed-by: Adam Kunicki <adam@streamsets.com>

diff --git a/dist/src/main/libexec/_sdc b/dist/src/main/libexec/_sdc
--- a/dist/src/main/libexec/_sdc
+++ b/dist/src/main/libexec/_sdc
@@ -152,6 +152,20 @@ else
   echo "WARN: could not determine Java environment version; expected 1.8, which are the supported versions" >&2
 fi
 
+# Verify correct JVM vendor
+JAVA_VENDOR=`$JAVA -XshowSettings:properties -version 2>&1 | grep -e 'java.vm.name' | sed -e 's/\(.*\)= \(.*\)/\2/'`
+if [[ ! "$JAVA_VENDOR" =~ "Java HotSpot(TM)" ]]
+then
+  echo "WARN: Detected non-Oracle JDK: $JAVA_VENDOR"
+
+  # And unless unsupported JDK is explicitly enabled, die
+  if [[ "${SDC_ALLOW_UNSUPPORTED_JDK}" != "true" ]]
+  then
+  echo "ERROR: Please install Oracle JDK or explicitly allow unsupported JDKs via SDC_ALLOW_UNSUPPORTED_JDK=true"
+    exit 1
+  fi
+fi
+
 if [ "${SDC_HEAPDUMP_ON_OOM}" = "true" ]
 then
   SDC_JAVA_OPTS="${SDC_JAVA_OPTS} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${SDC_HEAPDUMP_PATH}"
