SDC-15754. Update JVM Settings for JDK 11
Change-Id: I742c463b49e0fc67fd173fe05f4ba1d04a3876aa
Reviewed-on: https://review.streamsets.net/c/datacollector/+/34717
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>

diff --git a/dist/src/main/libexec/_sdc b/dist/src/main/libexec/_sdc
--- a/dist/src/main/libexec/_sdc
+++ b/dist/src/main/libexec/_sdc
@@ -179,17 +179,76 @@ then
   exit 1
 fi
 
-JAVA_VERSION=`$JAVA -version 2>&1 | grep -e 'version' | sed -e 's/.*"\([0-9]*\)\.\([0-9]*\)\.\([\_0-9]*\)"/\1\.\2/'`
-if [[ "$JAVA_VERSION" = '1.7' ]];
+# returns the JDK version.
+# 8 for 1.8.0_nn, 11 for 11-ea etc, and "no_java" for undetected
+jdk_version() {
+  local result
+  local java_cmd
+  if [[ -n $(type -p java) ]]
+  then
+    java_cmd=java
+  elif [[ (-n "$JAVA_HOME") && (-x "$JAVA_HOME/bin/java") ]]
+  then
+    java_cmd="$JAVA_HOME/bin/java"
+  fi
+  local IFS=$'\n'
+  # remove \r for Cygwin
+  local lines=$("$java_cmd" -Xms32M -Xmx32M -version 2>&1 | tr '\r' '\n')
+  if [[ -z $java_cmd ]]
+  then
+    result=no_java
+  else
+    for line in $lines; do
+      if [[ (-z $result) && ($line = *"version \""*) ]]
+      then
+        local ver=$(echo $line | sed -e 's/.*version "\(.*\)"\(.*\)/\1/; 1q')
+        # on macOS, sed doesn't support '?'
+        if [[ $ver = "1."* ]]
+        then
+          result=$(echo $ver | sed -e 's/1\.\([0-9]*\)\(.*\)/\1/; 1q')
+        else
+          result=$(echo $ver | sed -e 's/\([0-9]*\)\(.*\)/\1/; 1q')
+        fi
+      fi
+    done
+  fi
+  echo "$result"
+}
+
+JAVA_VERSION="$(jdk_version)"
+if [[ "$JAVA_VERSION" = '7' ]];
 then
-  echo "ERROR: Detected JDK7 that is no longer supported. Please upgrade to JDK8."
+  echo "ERROR: Detected JDK7 that is no longer supported. Please upgrade to JDK 8+."
   exit
-elif [[ "$JAVA_VERSION" = '1.8' ]];
+elif [[ "$JAVA_VERSION" = '8' ]];
 then
   echo "Java 1.8 detected; adding \$SDC_JAVA8_OPTS of \"${SDC_JAVA8_OPTS}\" to \$SDC_JAVA_OPTS"
   SDC_JAVA_OPTS="${SDC_JAVA_OPTS} ${SDC_JAVA8_OPTS}"
+
+  if [ "${SDC_GC_LOGGING}" = "true" ]
+  then
+    SDC_JAVA_OPTS="${SDC_JAVA_OPTS} -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:${SDC_LOG}/gc.log"
+  fi
+elif [[ "$JAVA_VERSION" = '11' ]];
+then
+  echo "Java 11 detected; adding \$SDC_JAVA11_OPTS of \"${SDC_JAVA11_OPTS}\" to \$SDC_JAVA_OPTS"
+  SDC_JAVA_OPTS="${SDC_JAVA_OPTS} ${SDC_JAVA11_OPTS}"
+
+  if [ "${SDC_GC_LOGGING}" = "true" ]
+  then
+    SDC_JAVA_OPTS="${SDC_JAVA_OPTS} -Xlog:gc:${SDC_LOG}/gc.log:time,uptime"
+  fi
+elif [[ "$JAVA_VERSION" = '14' ]];
+then
+  echo "Java 14 detected; adding \$SDC_JAVA14_OPTS of \"${SDC_JAVA14_OPTS}\" to \$SDC_JAVA_OPTS"
+  SDC_JAVA_OPTS="${SDC_JAVA_OPTS} ${SDC_JAVA14_OPTS}"
+
+  if [ "${SDC_GC_LOGGING}" = "true" ]
+  then
+    SDC_JAVA_OPTS="${SDC_JAVA_OPTS} -Xlog:gc:${SDC_LOG}/gc.log:time,uptime"
+  fi
 else
-  echo "WARN: could not determine Java environment version; expected 1.8, which are the supported versions" >&2
+  echo "WARN: could not determine Java environment version: \"${JAVA_VERSION}\" ; expected 1.8, 11 or 14, which are the supported versions" >&2
 fi
 
 # Verify correct JVM vendor
@@ -209,11 +268,6 @@ fi
 if [ "${SDC_HEAPDUMP_ON_OOM}" = "true" ]
 then
   SDC_JAVA_OPTS="${SDC_JAVA_OPTS} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${SDC_HEAPDUMP_PATH}"
-fi
-
-if [ "${SDC_GC_LOGGING}" = "true" ]
-then
-  SDC_JAVA_OPTS="${SDC_JAVA_OPTS} -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:${SDC_LOG}/gc.log"
 fi
 
 # Adding JVM Fatal Error Log file path
