SDC-1026. Ensure SDC policy file exists if security is enabled
Change-Id: I3b52bee025acc08ee474ff8bed1798b0439a48e7
Reviewed-on: https://review.streamsets.net/589
Reviewed-by: Brock Noland <brock@streamsets.com>

diff --git a/dist/src/main/libexec/_sdc b/dist/src/main/libexec/_sdc
--- a/dist/src/main/libexec/_sdc
+++ b/dist/src/main/libexec/_sdc
@@ -85,6 +85,16 @@ SDC_POLICY_FILE=""
 if [ "${SDC_SECURITY_MANAGER_ENABLED}" = "true" ]
 then
   SDC_POLICY_FILE=${SDC_POLICY_FILE:="file://${SDC_CONF}/sdc-security.policy"}
+  if [[ "$SDC_POLICY_FILE" =~ (file:)(.*) ]]
+  then
+      SDC_POLICY_FILE_FOR_VALIDATION="${BASH_REMATCH[2]}"
+  else
+      SDC_POLICY_FILE_FOR_VALIDATION="$SDC_POLICY_FILE"
+  fi
+  if [[ ! -f "$SDC_POLICY_FILE_FOR_VALIDATION" ]]
+  then
+    echo "WARN: Security is enabled and was unable to verify policy file '$SDC_POLICY_FILE'" 1>&2
+  fi
   SDC_SECURITY_MANAGER="-Djava.security.manager -Djava.security.policy=${SDC_POLICY_FILE}"
   SDC_JAVA_OPTS="${SDC_SECURITY_MANAGER} ${SDC_JAVA_OPTS}"
 fi
