SDC-340. Enable script for creating multi SDC homes

diff --git a/dist/src/main/bin/create-sdc b/dist/src/main/bin/create-sdc
--- a/dist/src/main/bin/create-sdc
+++ b/dist/src/main/bin/create-sdc
@@ -35,19 +35,24 @@ BASEDIR=`cd ${BASEDIR}/..;pwd`
 SDC_DIST=${BASEDIR}
 
 SDC_HOME=""
-SDC_PORT=""
+SDC_HTTP_PORT=""
+SDC_HTTPS_PORT=""
 while test $# -gt 0; do
   case "$1" in
     -home=*)
       SDC_HOME=`echo $1 | sed -e 's/^[^=]*=//g'`
       shift
       ;;
-    -port=*)
-      SDC_PORT=`echo $1 | sed -e 's/^[^=]*=//g'`
+    -httpPort=*)
+      SDC_HTTP_PORT=`echo $1 | sed -e 's/^[^=]*=//g'`
+      shift
+      ;;
+    -httpsPort=*)
+      SDC_HTTPS_PORT=`echo $1 | sed -e 's/^[^=]*=//g'`
       shift
       ;;
     -help)
-      echo "createsdc -home=<SDC_HOME_DIR> -port=<SDC_HTTP_PORT>"
+      echo "createsdc -home=<SDC_HOME_DIR> (-httpPort=<SDC_HTTP_PORT> | -httpsPort=<SDC_HTTPS_PORT>)"
       echo ""
       exit 0
       ;;
@@ -60,7 +65,15 @@ while test $# -gt 0; do
   esac
 done
 
-if [[ -z "${SDC_HOME}" || -z "${SDC_PORT}" ]]
+if [[ -z "${SDC_HOME}" ]]
+then
+  echo "Missing arguments, run 'createsdc -help'"
+  echo ""
+  $0 -help
+  exit 1
+fi
+
+if [[ -z "${SDC_HTTP_PORT}" && -z "${SDC_HTTPS_PORT}" ]]
 then
   echo "Missing arguments, run 'createsdc -help'"
   echo ""
@@ -75,21 +88,38 @@ then
   exit 1
 fi
 
+SDC_HTTP_PORT=${SDC_HTTP_PORT:="0"}
+SDC_HTTPS_PORT=${SDC_HTTPS_PORT:="0"}
+
 
 run mkdir "${SDC_HOME}"
 SDC_HOME=`cd ${SDC_HOME};pwd`
 
 run mkdir "${SDC_HOME}/bin"
 run mkdir "${SDC_HOME}/etc"
+run mkdir "${SDC_HOME}/libexec"
 run sed -e "s|#SDC_HOME#|${SDC_HOME}|" -e "s|#SDC_DIST#|${SDC_DIST}|" \
     < "${SDC_DIST}/bin/_sdc_prototype" > "${SDC_HOME}/bin/sdc"
 run chmod a+x "${SDC_HOME}/bin/sdc"
-run cp "${SDC_DIST}/etc/log4j.properties" "${SDC_HOME}/etc"
-run sed -e "s|http.port=8080|http.port=${SDC_PORT}|" \
-    < "${SDC_DIST}/etc/sdc.properties" > "${SDC_HOME}/etc/sdc.properties"
+run cp -r -p "${SDC_DIST}/etc/"* "${SDC_HOME}/etc/"
+run cp -r -p "${SDC_DIST}/libexec/"* "${SDC_HOME}/libexec/"
+run rm "${SDC_HOME}/etc/sdc.properties"
+
+SED_OPTIONS=""
+if [ -n "${SDC_HTTP_PORT}" ]
+then
+  SED_OPTIONS="-e s|http.port=.*$|http.port=${SDC_HTTP_PORT}|"
+fi
+
+if [ -n "${SDC_HTTPS_PORT}" ]
+then
+  SED_OPTIONS="${SED_OPTIONS} -e s|https.port=.*$|https.port=${SDC_HTTPS_PORT}|"
+fi
+
+run sed ${SED_OPTIONS} < "${SDC_DIST}/etc/sdc.properties" > "${SDC_HOME}/etc/sdc.properties"
 
 echo ""
-echo "New sdc created at ${SDC_HOME} on port ${SDC_PORT}"
+echo "New sdc created at ${SDC_HOME} on HTTP port ${SDC_HTTP_PORT} and HTTPS port ${SDC_HTTPS_PORT}"
 echo ""
 echo "Use '${SDC_HOME}/bin/sdc' to run the new sdc"
 echo ""
